packages:
- 'hgeometry'
- 'hgeometry-combinatorial'
- 'hgeometry-ipe'
- 'hgeometry-examples'
- 'hgeometry-svg'
- 'hgeometry-test'
extra-deps:
- vector-circular-0.1.2@sha256:f13b612cace73ec64e7f5387d8c48f4cadb3fc84666d215493fbfcbd9ae93219,1468
build:
  # library-profiling: true
  # executable-profiling: true
resolver: lts-17.0
