flags:
    hgeometry:
        examples: true
        interactive: false
packages:
- '.'
extra-deps:
- approximate-equality-1.1.0.2
- type-level-natural-number-2.0
- doctest-discover-0.2.0.0
- data-clist-0.1.2.2@sha256:4d70add0a200a178853cd37c6469101bac3c36aebb3aa9c503ff225211b1a8c9
build:
  # library-profiling: true
  # executable-profiling: true
extra-lib-dirs:
- /usr/lib
resolver: lts-13.0
